######################################################################
# Automatically generated by qmake (3.0) sáb. abr. 22 19:43:37 2017
######################################################################

QT       += core websockets
QT       -= gui

TEMPLATE = app
TARGET = qtwebsocketserver
INCLUDEPATH += .

# Input
HEADERS += echoserver.h ID003.hpp Thread.hpp
SOURCES += echoserver.cpp ID003.cpp main.cpp Thread.cpp
